include("continuous_space.jl")
include("multi_continuous_space.jl")
include("discrete_space.jl")
include("empty_space.jl")
include("multi_discrete_space.jl")
include("vect_space.jl")
include("dict_space.jl")
