name = "MultiAgentReinforcementLearning"
uuid = "c65af49a-feda-45df-9d14-b4e40efca6f2"
authors = ["Panajiotis Keßler <panajiotiskessler@gmail.com>"]
version = "0.1.0"

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReinforcementLearningBase = "e575027e-6cd6-5018-9292-cdc6200d2b44"
ReinforcementLearningCore = "de1b191a-4ae0-4afa-a27b-92d07f46b2d6"
ReinforcementLearningTrajectories = "6486599b-a3cd-4e92-a99a-2cea90cc8c3c"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BSON = "0.3"
Flux = "0.13"
ReinforcementLearningBase = "0.11"
ReinforcementLearningCore = "0.9"
ReinforcementLearningTrajectories = "0.1"
julia = "1.7"

[extras]
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
ReinforcementLearningEnvironments = "25e41dd2-4622-11e9-1641-f1adca772921"
ReinforcementLearningZoo = "d607f57d-ee1e-4ba7-bcf2-7734c1e31854"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "CommonRLInterface", "ReinforcementLearningZoo", "ReinforcementLearningEnvironments", "PyCall", "POMDPs", "POMDPTools"]
